"""add start_at to tasks

Revision ID: 81a4ab8983eb
Revises: ced1196a6665
Create Date: 2025-12-30 17:19:24.823592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a4ab8983eb'
down_revision: Union[str, Sequence[str], None] = 'ced1196a6665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_at')
    # ### end Alembic commands ###
