"""changed expires_at

Revision ID: df459abf3567
Revises: f211132eb852
Create Date: 2026-02-05 18:47:33.807495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df459abf3567'
down_revision: Union[str, Sequence[str], None] = 'f211132eb852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reset_tokens",
        "used_at",
        type_=sa.DateTime(timezone=True),
        postgresql_using="used_at AT TIME ZONE 'UTC'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reset_tokens",
        "used_at",
        type_=sa.DateTime(timezone=False),
        postgresql_using="used_at",
    )
    # ### end Alembic commands ###
